default:
  image: flemay/musketeers
  after_script:
    - make clean

build:
  script:
    - make build
    - make scan
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  except:
    - tags

publish:
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
  script:
    - make build
    - make scan
    - make publishGitlab
    - make publishDockerhub
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  only:
    - tags
