image: flemay/musketeers

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.8-dind

cache:
  paths:
    - .cache

build:
  script:
    - make build
    - make scan
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  except:
    - tags

publish:
  before_script:
    - docker login -u gitlab-ci-token -p ${CI_BUILD_TOKEN} ${CI_REGISTRY}
    - docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD}
  script:
    - make build
    - make scan
    - make publishGitlab
    - make publishDockerhub
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
  only:
    - tags
