name: Build Container

on:
  push:

permissions:
  contents: read
  pages: write
  security-events: write
  packages: write
  id-token: write

env:
  RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
  PROJECT_URL: ${{ github.server_url }}/${{ github.repository }}
  COMMIT_SHA: ${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build the Docker image
        run: |
          make build
          make badges
          make scan

      - name: Upload artifact
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: actions/upload-pages-artifact@v4
        with:
          path: public

      - name: Upload results to the GitHub Security tab
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Login to Docker Hub
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Log in to GHCR
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Docker Hub and GHCR
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        run: |
          make publish

  deploy:
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    environment:
      name: github-pages
      url: ${{ steps.deploy-to-gh-pages.outputs.url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deploy-to-gh-pages
        uses: actions/deploy-pages@v4
